### ISSUE TITLE
Wrong value returned from function call and array

### ISSUE THREAD

**Issue by gabidavila** [learn-co-curriculum/introduction-to-functions-lab#2]
This lesson show `spinach salad` as the last element in the array, but at execution time, `eggs` is the last statement:

<img width="1116" alt="screen shot 2018-04-08 at 11 59 22" src="https://user-images.githubusercontent.com/340055/38469540-63d879ce-3b24-11e8-898e-f2475542515f.png">

**Comment by tkoar** [comment]
This has been updated and the examples should now reflect the correct return values
